import type {AppLocale} from "@/i18n/routing";

type SummaryPair = {en: string; tr: string};

// Short, original editorial copy for the atlas UI. Imported source summaries remain
// available for attribution, but are never used as the displayed biography.
const SUMMARIES: Record<string, SummaryPair> = {
  Q4604: {en: "Confucius developed an ethical vision centered on humane conduct, learning, ritual, and responsible public service. His teaching made character formation the foundation of a stable society.", tr: "Konfüçyüs; insaniyet, öğrenme, ritüel ve sorumlu kamu hizmeti üzerine kurulu bir etik anlayış geliştirdi. Öğretisi, düzenli toplumun temelini karakter eğitiminde gördü."},
  Q913: {en: "Socrates made philosophical inquiry a shared civic practice, testing beliefs through demanding questions. He treated self-knowledge and moral integrity as more valuable than reputation or wealth.", tr: "Sokrates, felsefi araştırmayı zorlayıcı sorularla yürütülen ortak bir yurttaşlık pratiğine dönüştürdü. Öz bilgiyi ve ahlaki tutarlılığı ün ya da servetten üstün tuttu."},
  Q859: {en: "Plato linked ethics, politics, education, and metaphysics in a single account of the good life. His dialogues explore how reason can guide both the individual soul and the city.", tr: "Platon; etik, siyaset, eğitim ve metafiziği iyi yaşamın tek bir açıklamasında birleştirdi. Diyalogları, aklın bireysel ruhu ve şehri nasıl yönlendirebileceğini araştırır."},
  Q868: {en: "Aristotle organized inquiry across logic, nature, psychology, ethics, and politics. He explained flourishing as the practiced activity of a rational life shaped by habits and judgment.", tr: "Aristoteles; mantık, doğa, psikoloji, etik ve siyaset alanlarında sistemli bir araştırma düzeni kurdu. Mutluluğu, alışkanlıklar ve yargıyla biçimlenen akıl sahibi yaşamın etkinliği olarak açıkladı."},
  Q43216: {en: "Epicurus taught that a tranquil life grows from modest pleasures, friendship, and freedom from needless fear. He challenged superstition by treating nature as intelligible rather than threatening.", tr: "Epikür, dingin yaşamın ölçülü hazlardan, dostluktan ve gereksiz korkulardan kurtulmaktan doğduğunu savundu. Doğayı tehdit değil, anlaşılabilir bir düzen olarak ele alarak batıl inançlara karşı çıktı."},
  Q11903: {en: "Hypatia became a leading teacher of mathematics and philosophy in late antique Alexandria. Her work represents the continuing exchange between scientific reasoning, Neoplatonic thought, and public education.", tr: "İskenderiyeli Hypatia, geç antik çağ İskenderiyesi'nde matematik ve felsefenin önde gelen öğretmenlerinden oldu. Çalışmaları bilimsel akıl, Yeni Platonculuk ve kamusal eğitim arasındaki sürekliliği temsil eder."},
  Q8011: {en: "Avicenna joined Aristotelian philosophy with medical and metaphysical investigation. His account of existence, intellect, and the self shaped philosophical medicine and scholarship across the Islamic world and Europe.", tr: "İbn-i Sina, Aristotelesçi felsefeyi tıp ve metafizik araştırmayla birleştirdi. Varlık, akıl ve benlik açıklamaları İslam dünyası ile Avrupa'daki felsefi ve tıbbi düşünceyi etkiledi."},
  Q9191: {en: "Descartes sought a secure starting point for knowledge by examining doubt, consciousness, and method. His work helped establish modern rationalism and a new ideal of mathematical clarity.", tr: "Descartes; kuşku, bilinç ve yöntem üzerinden bilgi için güvenilir bir başlangıç aradı. Çalışmaları modern akılcılığın ve matematiksel açıklık idealinin oluşmasına katkı verdi."},
  Q101638: {en: "Wollstonecraft argued that education should cultivate the reason and independence of women. She connected personal freedom with political equality and criticized customs that treated dependency as virtue.", tr: "Wollstonecraft, eğitimin kadınların aklını ve bağımsızlığını geliştirmesi gerektiğini savundu. Kişisel özgürlüğü siyasal eşitlikle ilişkilendirerek bağımlılığı erdem sayan gelenekleri eleştirdi."},
  Q9358: {en: "Nietzsche reworked European moral and religious inheritance through genealogy, critique, and experiments in style. He asked how values are created and what forms of life they enable.", tr: "Nietzsche, Avrupa'nın ahlaki ve dinsel mirasını soybilim, eleştiri ve biçimsel deneylerle yeniden düşündü. Değerlerin nasıl üretildiğini ve hangi yaşam biçimlerini mümkün kıldığını sorguladı."},
  Q36303: {en: "Thales explained the world through a natural principle rather than a genealogy of gods. His search for an underlying unity marks an early turn toward rational cosmological inquiry.", tr: "Thales, dünyayı tanrıların soy kütüğü yerine doğal bir ilkeyle açıklamaya çalıştı. Temel bir birlik arayışı, akılcı kozmolojik araştırmaya yönelen erken bir dönüşü gösterir."},
  Q42458: {en: "Anaximander proposed the apeiron, an indefinite source from which opposites emerge and return. His cosmology placed natural change within an ordered process rather than divine whim.", tr: "Anaksimandros, karşıtların ortaya çıkıp geri döndüğü belirsiz kaynak olarak apeiron kavramını önerdi. Kozmolojisi, doğal değişimi tanrısal keyiften çok düzenli bir süreç içinde düşündü."},
  Q80612: {en: "Anaximenes identified air as the basic principle of nature and explained diversity through rarefaction and condensation. His account connected cosmic structure with observable physical change.", tr: "Miletli Anaksimenes, havayı doğanın temel ilkesi saydı ve çeşitliliği seyrelme ile yoğunlaşmayla açıkladı. Açıklaması kozmik yapıyı gözlenebilir fiziksel değişimle ilişkilendirdi."},
  Q10261: {en: "Pythagoras joined numerical order, musical proportion, ritual discipline, and the transmigration of souls. His community made mathematical pattern a model for both knowledge and conduct.", tr: "Pisagor; sayısal düzeni, müzikal oranı, ritüel disiplini ve ruhların göçünü bir araya getirdi. Topluluğu, matematiksel örüntüyü bilgi ve davranış için bir model saydı."},
  Q131671: {en: "Xenophanes criticized human-shaped gods and emphasized the limits of certainty. His reflections opened a path toward more critical theology and careful accounts of knowledge.", tr: "Ksenofanes, insan biçimli tanrıları eleştirdi ve kesinliğin sınırlarını vurguladı. Düşünceleri eleştirel teolojiye ve bilginin daha temkinli açıklamalarına bir yol açtı."},
  Q41155: {en: "Heraclitus described reality as ordered change in which conflict and transformation belong together. His language of logos presents understanding as an attunement to a common world.", tr: "Heraklitos, gerçekliği çatışma ve dönüşümün birlikte işlediği düzenli bir değişim olarak anlattı. Logos kavramı, anlamayı ortak dünyayla uyum kurmak şeklinde sunar."},
  Q125551: {en: "Parmenides argued that thought must follow what is, rejecting becoming as a route to truth. His poem forced later philosophers to clarify the relation between reason, appearance, and change.", tr: "Parmenides, düşüncenin var olana uyması gerektiğini savunarak oluşu hakikate giden yol olarak reddetti. Şiiri, sonraki filozofları akıl, görünüş ve değişim ilişkisini açıklamaya zorladı."},
  Q83041: {en: "Anaxagoras explained the cosmos through an ordering Nous acting upon an initially mixed whole. His natural philosophy made intelligence a principle of cosmic organization.", tr: "Anaksagoras, kozmosu başlangıçta karışık olan bütünü düzenleyen Nous ilkesiyle açıkladı. Doğa felsefesi, zekâyı kozmik düzenin bir ilkesi haline getirdi."},
  Q83375: {en: "Empedocles described nature through four enduring elements and two forces, Love and Strife. Cycles of union and separation explained both cosmic order and living change.", tr: "Empedokles, doğayı dört kalıcı unsur ile Sevgi ve Çatışma adlı iki güç üzerinden açıkladı. Birleşme ve ayrılma döngüleri kozmik düzeni ve canlı değişimini açıklar."},
  Q132157: {en: "Zeno of Elea used paradoxes to challenge ordinary accounts of motion and plurality. His arguments made conceptual rigor central to debates about space, time, and change.", tr: "Elealı Zenon, paradokslarıyla hareket ve çokluk hakkındaki gündelik açıklamalara meydan okudu. Argümanları, uzay, zaman ve değişim tartışmalarında kavramsal titizliği merkezileştirdi."},
  Q169243: {en: "Protagoras treated human judgment as central to questions of truth and civic life. His teaching connected rhetoric, education, and the practical choices made in a changing city.", tr: "Protagoras, hakikat ve yurttaşlık sorularında insan yargısını merkeze aldı. Öğretisi retorik, eğitim ve değişen şehirde verilen pratik kararları birbirine bağladı."},
  Q179785: {en: "Gorgias explored the power and limits of language through provocative arguments about being, knowledge, and persuasion. His work made rhetoric a subject of philosophical scrutiny.", tr: "Gorgias, varlık, bilgi ve ikna üzerine kışkırtıcı argümanlarla dilin gücünü ve sınırlarını araştırdı. Çalışmaları retoriği felsefi incelemenin konusu yaptı."},
  Q41980: {en: "Democritus explained nature through atoms moving in the void and treated human understanding as part of that natural order. His ethical writings valued cheerfulness, measure, and self-command.", tr: "Demokritos, doğayı boşlukta hareket eden atomlarla açıkladı ve insan anlayışını bu doğal düzenin parçası saydı. Etiği neşe, ölçü ve öz denetimi öne çıkardı."},
  Q179149: {en: "Antisthenes emphasized discipline, independence, and the sufficiency of virtue. His challenge to convention helped shape the Cynic practice of living simply and speaking frankly.", tr: "Antisthenes, disiplin, bağımsızlık ve erdemin yeterliliğini vurguladı. Geleneklere meydan okuması, sade yaşama ve açık konuşma pratiğiyle Kinizmi biçimlendirdi."},
  Q189506: {en: "Aristippus defended intelligent pleasure and the ability to remain free within changing circumstances. His Cyrenaic approach made present experience and self-mastery central to ethics.", tr: "Aristippos, bilinçli hazzı ve değişen koşullar içinde özgür kalma yeteneğini savundu. Kirene yaklaşımı, şimdiki deneyimi ve öz yönetimi etiğin merkezine aldı."},
  Q59180: {en: "Diogenes of Sinope turned philosophy into a public experiment in simplicity, candor, and independence. His Cynic life questioned status, luxury, and the habits that hide human needs.", tr: "Sinoplu Diyojen, felsefeyi sadelik, açık sözlülük ve bağımsızlık üzerine kamusal bir deneye dönüştürdü. Kinik yaşamı statüyü, lüksü ve insan ihtiyaçlarını örten alışkanlıkları sorguladı."},
  Q160362: {en: "Theophrastus extended Peripatetic inquiry into botany, character, language, and natural observation. He combined Aristotle's systematic interests with a patient attention to variation in living things.", tr: "Theophrastus, Peripatetik araştırmayı botanik, karakter, dil ve doğa gözlemine genişletti. Aristoteles'in sistemli ilgilerini canlılardaki çeşitliliğe yönelik sabırlı dikkatle birleştirdi."},
  Q192313: {en: "Pyrrho made suspension of judgment a practical route toward freedom from disturbance. His skeptical stance questioned dogmatic certainty while leaving room for calm, attentive living.", tr: "Pyrrhon, yargıyı askıya almayı zihinsel sarsıntıdan kurtulmanın pratik bir yolu saydı. Kuşkucu tutumu dogmatik kesinliği sorgularken sakin ve dikkatli yaşama alan bıraktı."},
  Q171303: {en: "Zeno of Citium founded Stoicism, teaching that a good life follows nature through reason, discipline, and justice. His school joined physics, ethics, and logic into one practice of wisdom.", tr: "Kıbrıslı Zenon, iyi yaşamın akıl, disiplin ve adaletle doğaya uygun yaşamak olduğunu öğreten Stoacılığı kurdu. Okulu fizik, etik ve mantığı tek bir bilgelik pratiğinde birleştirdi."},
  Q310149: {en: "Cleanthes preserved and developed early Stoic ideas, emphasizing the rational structure of nature and the discipline of assent. His surviving hymn presents the cosmos as a moral order.", tr: "Cleanthes, erken Stoacı düşünceleri koruyup geliştirdi; doğanın akılcı yapısını ve onay verme disiplinini vurguladı. Günümüze kalan ilahisi kozmosu ahlaki bir düzen olarak sunar."},
  Q211411: {en: "Chrysippus systematized Stoic logic, physics, and ethics with exceptional breadth. He argued that understanding causal order can support responsibility, emotional training, and a coherent life.", tr: "Hrisippos, Stoacı mantık, fizik ve etiği olağanüstü kapsamla sistemleştirdi. Nedensel düzeni anlamanın sorumluluğu, duygu eğitimini ve tutarlı yaşamı destekleyebileceğini savundu."},
};

export function editorialSummary(id: string, locale: AppLocale) {
  return SUMMARIES[id]?.[locale] ?? null;
}
